language: node_js
node_js:
  - node

before_script:
  - set -e
  - cd backend
  - npm i
  - cd ../frontend
  - npm i
  - npm i codecov
  - cd ..

script:
  - set -e

  # Environment variables
  - export REPO_NAME=$(echo $TRAVIS_REPO_SLUG | awk -F/ '{ print tolower($2) }')

  # Frontend
  - cd frontend
  - npm test -- --coverage
  - ./node_modules/.bin/codecov
  - npm run build
  - cd ..

  # Backend
  - cd backend
  - npm test
  - cd ..
