language: node_js
node_js:
  - node
cache: npm

before_script:
  - set -e
  - cd backend
  - npm ci
  - cd ../frontend
  - npm ci
  - npm i codecov
  - cd ..

script:
  - set -e

  # Frontend
  - cd frontend
  - npm test -- --coverage
  - ./node_modules/.bin/codecov
  - npm run build
  - cd ..

  # Backend
  - cd backend
  - npm test
  - cd ..
